root = "."         
tmp_dir = "tmp"    

[build]
  cmd = "go build -o ./tmp/pocketbase_server_dev main.go hooks.go" 
  bin = "./tmp/pocketbase_server_dev serve --http=0.0.0.0:8090" 
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "pb_data", "migrations"]
  stop_on_error = true
  delay = 1000 

[log]
  time = true

[misc]
  clean_on_exit = true